"""Claude Away -- capacity-aware autonomous work planning for Claude Code.

This package currently contains **Milestone 1: the deterministic state core** only.

What exists today:

* versioned SQLite storage that is the authoritative machine state;
* the documented eight-state task lifecycle with enforced transition guards;
* the evidence gate, which makes ``VERIFYING -> DONE`` impossible without passing
  evidence recorded by the current attempt;
* deterministic DAG validation and readiness computation;
* attempts, append-only evidence, leases and an append-only audit event ledger;
* typed domain errors and a thin ``awayctl`` inspection CLI.

What does **not** exist yet (see ``docs/ROADMAP.md`` for the milestone that owns each):
Git isolation, Claude execution, verification command execution, the capacity provider
and scheduler, the LLM planner, plugin skills, and the long-running supervisor.

The organising principle is that this layer owns facts and an LLM owns judgement:
``DONE`` is a claim backed by evidence, not a sentence generated by a model.
"""

from __future__ import annotations

__all__ = ["__version__"]

__version__ = "0.0.1"
