"""Evidence recording and the evidence gate.

This module implements the project's central invariant:

    DONE is a claim backed by evidence, not a sentence generated by Claude.

Concretely, ``VERIFYING -> DONE`` is impossible unless **every required verification
requirement** of the task has a *passing* evidence record produced by the *current
attempt* against the *current definition* of that requirement.

Three separate staleness problems have to be solved, and it is worth being explicit about
each because only the first is obvious:

1. **Wrong attempt.** Evidence from attempt #1 must not satisfy attempt #2. Solved by
   scoping the gate query to the current attempt id.

2. **Changed requirement.** A replan may edit a requirement while keeping its id --
   ``unit-tests`` might change from ``pytest tests/smoke`` to ``pytest tests/``. Evidence
   recorded against the old command must not satisfy the new one. Solved by storing a
   ``spec_hash`` of the requirement's semantic content on every evidence row and requiring
   it to match the requirement's current hash.

3. **Superseded result.** Within one attempt a check may legitimately be re-run after a
   fix: fail, then pass. The gate takes the *latest* evidence per requirement, so the pass
   counts -- while the failure remains permanently in history, because that record is what
   stops a later run from pretending verification was clean all along.

Evidence is append-only. That is enforced by SQLite triggers (see :mod:`claude_away.core.db`),
not by convention, so no code path -- including a buggy one in this package -- can quietly
rewrite it.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping
from dataclasses import dataclass
from enum import Enum
from typing import Any

from claude_away.clock import parse_timestamp, to_iso
from claude_away.core.db import Database, dumps, loads
from claude_away.core.models import (
    EvidenceRecord,
    EvidenceResult,
    EvidenceType,
    VerificationRequirement,
    VerificationType,
)
from claude_away.errors import NotFoundError, ValidationError

__all__ = [
    "COMPATIBLE_EVIDENCE_TYPES",
    "GateReport",
    "evaluate_gate",
    "list_evidence",
    "record_evidence",
    "verification_spec_hash",
]

_MAX_SUMMARY_CHARS = 4_000
"""Summaries are bounded. Evidence is a ledger, not a log sink."""

MAX_RUNS_PER_REQUIREMENT_PER_ATTEMPT = 3
"""How many times one requirement may be recorded within a single attempt.

Latest-wins resolution is correct (see :func:`evaluate_gate`) but it has an obvious abuse:
re-run a flaky check until it happens to pass. A hard bound turns that into a deterministic
refusal rather than a judgement call. The failures stay in the ledger either way, so
"passed on run 3 of 3" remains visible in the return briefing instead of being laundered
into a clean result.
"""


COMPATIBLE_EVIDENCE_TYPES: dict[VerificationType, frozenset[EvidenceType]] = {
    # Which kinds of evidence can honestly discharge which kind of requirement.
    #
    # This is the evidence-side half of STATE_MODEL's rule that "tasks with deterministic
    # acceptance checks cannot replace those checks with an LLM opinion". Enforcing it only
    # on the requirement side left the rule trivially defeatable: a required `command`
    # check could be satisfied by an `EvidenceType.REVIEW` row saying "I read it, the tests
    # would pass" -- the command never ran, and the gate opened anyway.
    VerificationType.COMMAND: frozenset(
        {
            EvidenceType.COMMAND,
            EvidenceType.TEST,
            EvidenceType.LINT,
            EvidenceType.TYPECHECK,
            EvidenceType.BUILD,
        }
    ),
    VerificationType.ARTIFACT: frozenset({EvidenceType.ARTIFACT}),
    VerificationType.GIT: frozenset({EvidenceType.GIT, EvidenceType.PULL_REQUEST}),
    VerificationType.REVIEW: frozenset({EvidenceType.REVIEW}),
    VerificationType.MANUAL: frozenset({EvidenceType.MANUAL_APPROVAL}),
}


_OPERATIVE_FIELDS: dict[VerificationType, tuple[str, ...]] = {
    # What actually defines "the check" differs by type. Hashing the fields that carry the
    # meaning -- and only those -- is what makes staleness detection precise instead of
    # either too eager or too lax.
    VerificationType.COMMAND: ("command",),
    VerificationType.ARTIFACT: ("path",),
    VerificationType.GIT: ("description",),
    VerificationType.REVIEW: ("description",),
    VerificationType.MANUAL: ("description",),
}


def verification_spec_hash(
    *,
    type: VerificationType | str,
    command: str | None = None,
    path: str | None = None,
    description: str | None = None,
) -> str:
    """Hash the semantic content of a verification requirement.

    The hash covers the type plus that type's *operative* fields -- the ones that define
    what is actually being checked:

    ==========  ===============================================================
    ``command``  the command string
    ``artifact`` the path
    ``git``      the description (it states the repository fact being asserted)
    ``review``   the description (it *is* the review criteria)
    ``manual``   the description (it *is* what the human is approving)
    ==========  ===============================================================

    Two exclusions are deliberate and each closes a specific failure:

    * The requirement ``id`` is excluded because it is the lookup key, not content.
    * ``required`` is excluded because flipping a check from optional to mandatory does not
      change *what* was checked. The evidence genuinely proved the check; invalidating it
      would force a pointless re-run.

    Type-scoping the description matters in both directions. Including it for every type
    would mean fixing a typo in a command's commentary invalidates a passing test suite.
    Excluding it for every type would open a real hole: changing a ``manual`` requirement
    from "approve the API design" to "approve the production deploy" would keep the id and
    type identical, and a human's earlier sign-off would silently satisfy the new one.
    """
    verification_type = type if isinstance(type, VerificationType) else VerificationType(str(type))
    values = {"command": command, "path": path, "description": description}
    payload: dict[str, str] = {"type": verification_type.value}
    for field_name in _OPERATIVE_FIELDS[verification_type]:
        payload[field_name] = values[field_name] or ""

    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


class GateReason(str, Enum):
    """Why the gate reached its verdict. The supervisor branches on this, never on prose."""

    SATISFIED = "satisfied"
    NO_REQUIRED_REQUIREMENTS = "no_required_requirements"
    UNSATISFIED_REQUIRED = "unsatisfied_required"
    NO_ACTIVE_ATTEMPT = "no_active_attempt"


@dataclass(frozen=True, slots=True)
class GateReport:
    """The outcome of evaluating the evidence gate for one task.

    Structured rather than prose: the supervisor branches on these fields, and
    ``awayctl status --json`` renders them directly.
    """

    task_id: str
    attempt_id: str | None
    satisfied: bool
    reason: GateReason
    required_total: int
    missing: tuple[str, ...]
    """Required requirements with no usable evidence from the current attempt."""

    failed: tuple[str, ...]
    """Required requirements whose latest usable evidence did not pass."""

    stale: tuple[str, ...]
    """Requirements whose only evidence was recorded against an older definition.

    Reported separately from ``missing`` purely as a diagnostic -- these still block the
    gate. The distinction tells an operator "a replan changed this check" rather than
    "nobody ever ran it", which are very different things to debug.
    """

    satisfied_ids: tuple[str, ...]
    optional_failed: tuple[str, ...]
    """Optional requirements whose latest evidence did not pass.

    Never blocking, never hidden. A silently swallowed optional failure is how a project
    ends up with a lint suite nobody notices has been broken for a week.
    """

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_id": self.task_id,
            "attempt_id": self.attempt_id,
            "satisfied": self.satisfied,
            "reason": self.reason.value,
            "required_total": self.required_total,
            "missing": list(self.missing),
            "failed": list(self.failed),
            "stale": list(self.stale),
            "satisfied_ids": list(self.satisfied_ids),
            "optional_failed": list(self.optional_failed),
        }


def record_evidence(
    db: Database,
    *,
    task_id: str,
    type: EvidenceType,
    result: EvidenceResult,
    summary: str,
    attempt_id: str | None = None,
    verification_id: str | None = None,
    metadata: Mapping[str, Any] | None = None,
) -> EvidenceRecord:
    """Append one evidence record.

    When ``verification_id`` is given, the requirement's current ``spec_hash`` is captured
    on the row. That snapshot is what later lets the gate tell "this proves the check we
    are asking about" from "this proves a check that has since been redefined".

    Note that no redaction happens here yet, but the boundary is deliberate: ``summary``
    and ``metadata`` are the only fields that will ever carry command output, so a future
    redaction pass has exactly two places to cover rather than being scattered.
    """
    if not summary:
        raise ValidationError("evidence summary must not be empty", task_id=task_id)

    if verification_id is not None and attempt_id is None:
        # Unattributed evidence cannot be judged: the gate is attempt-scoped, so a row with
        # no attempt would only ever match a gate evaluated with no attempt -- which is
        # exactly the state a suspended run leaves behind. Refuse it at the source; a
        # database CHECK enforces the same rule one layer down.
        raise ValidationError(
            "evidence for a verification requirement must name the attempt that produced it",
            task_id=task_id,
            verification_id=verification_id,
        )

    created_at = to_iso(db.clock.now())
    truncated = (
        summary
        if len(summary) <= _MAX_SUMMARY_CHARS
        else (summary[: _MAX_SUMMARY_CHARS - 3] + "...")
    )

    spec_hash: str | None = None
    required_at_run: int | None = None

    # Every check below is a read that the following write depends on, so all of it lives
    # in one BEGIN IMMEDIATE transaction. Validating first and inserting afterwards would
    # let two concurrent recorders both observe "budget not yet spent" and then both write,
    # which is precisely the re-run-until-green laundering the budget exists to stop.
    with db.transaction() as con:
        if con.execute("SELECT 1 FROM tasks WHERE id = ?", (task_id,)).fetchone() is None:
            raise NotFoundError("task", task_id)

        if verification_id is not None:
            row = con.execute(
                "SELECT spec_hash, required, type FROM verification_requirements "
                "WHERE task_id = ? AND verification_id = ?",
                (task_id, verification_id),
            ).fetchone()
            if row is None:
                raise NotFoundError("verification requirement", f"{task_id}/{verification_id}")
            spec_hash = str(row["spec_hash"])
            required_at_run = int(row["required"])

            requirement_type = VerificationType(str(row["type"]))
            if type not in COMPATIBLE_EVIDENCE_TYPES[requirement_type]:
                raise ValidationError(
                    "evidence type cannot discharge this requirement type",
                    task_id=task_id,
                    verification_id=verification_id,
                    requirement_type=requirement_type.value,
                    evidence_type=type.value,
                    acceptable=sorted(e.value for e in COMPATIBLE_EVIDENCE_TYPES[requirement_type]),
                )

            # Bound re-runs of the same requirement within one attempt. Counting the
            # current spec_hash only means that legitimately *changing* a check resets the
            # budget, while hammering an unchanged flaky check does not.
            used = con.execute(
                "SELECT COUNT(*) AS n FROM evidence "
                " WHERE task_id = ? AND verification_id = ? AND requirement_spec_hash = ? "
                "   AND attempt_id IS ?",
                (task_id, verification_id, spec_hash, attempt_id),
            ).fetchone()
            if used is not None and int(used["n"]) >= MAX_RUNS_PER_REQUIREMENT_PER_ATTEMPT:
                raise ValidationError(
                    "verification run budget exhausted for this requirement in this attempt",
                    task_id=task_id,
                    verification_id=verification_id,
                    attempt_id=attempt_id,
                    budget=MAX_RUNS_PER_REQUIREMENT_PER_ATTEMPT,
                )

        if attempt_id is not None:
            attempt = con.execute(
                "SELECT task_id, outcome FROM attempts WHERE id = ?", (attempt_id,)
            ).fetchone()
            if attempt is None:
                raise NotFoundError("attempt", attempt_id)
            if attempt["outcome"] is not None:
                # A finished attempt is history. Appending to its ledger afterwards would
                # let a sealed fail be followed by a pass, laundering the record of what
                # actually happened during that run.
                raise ValidationError(
                    "cannot record evidence against a finished attempt",
                    task_id=task_id,
                    attempt_id=attempt_id,
                    outcome=str(attempt["outcome"]),
                )
            if str(attempt["task_id"]) != task_id:
                raise ValidationError(
                    "attempt belongs to a different task",
                    attempt_id=attempt_id,
                    attempt_task_id=str(attempt["task_id"]),
                    task_id=task_id,
                )

        cursor = con.execute(
            "INSERT INTO evidence("
            "  task_id, attempt_id, verification_id, requirement_spec_hash,"
            "  type, result, summary, metadata, created_at, required_at_run"
            ") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (
                task_id,
                attempt_id,
                verification_id,
                spec_hash,
                type.value,
                result.value,
                truncated,
                dumps(dict(metadata or {})),
                created_at,
                required_at_run,
            ),
        )
        evidence_id = int(cursor.lastrowid or 0)

    return EvidenceRecord(
        id=evidence_id,
        task_id=task_id,
        attempt_id=attempt_id,
        verification_id=verification_id,
        requirement_spec_hash=spec_hash,
        type=type,
        result=result,
        summary=truncated,
        created_at=parse_timestamp(created_at),
        metadata=dict(metadata or {}),
    )


def list_evidence(
    db: Database,
    task_id: str,
    *,
    attempt_id: str | None = None,
) -> list[EvidenceRecord]:
    """Return evidence for a task in insertion order (oldest first)."""
    sql = (
        "SELECT id, task_id, attempt_id, verification_id, requirement_spec_hash,"
        "       type, result, summary, metadata, created_at "
        "FROM evidence WHERE task_id = ?"
    )
    params: list[Any] = [task_id]
    if attempt_id is not None:
        sql += " AND attempt_id = ?"
        params.append(attempt_id)
    sql += " ORDER BY id"

    return [
        EvidenceRecord(
            id=int(row["id"]),
            task_id=str(row["task_id"]),
            attempt_id=row["attempt_id"],
            verification_id=row["verification_id"],
            requirement_spec_hash=row["requirement_spec_hash"],
            type=EvidenceType(row["type"]),
            result=EvidenceResult(row["result"]),
            summary=str(row["summary"]),
            created_at=parse_timestamp(str(row["created_at"])),
            metadata=loads(row["metadata"]),
        )
        for row in db.query(sql, params)
    ]


def load_requirements(db: Database, task_id: str) -> list[VerificationRequirement]:
    """Load a task's declared verification contract in stable order."""
    rows = db.query(
        "SELECT verification_id, type, required, command, path, description, spec_hash "
        "FROM verification_requirements WHERE task_id = ? ORDER BY position, verification_id",
        (task_id,),
    )
    return [
        VerificationRequirement(
            id=str(row["verification_id"]),
            type=VerificationType(row["type"]),
            required=bool(row["required"]),
            spec_hash=str(row["spec_hash"]),
            command=row["command"],
            path=row["path"],
            description=row["description"],
        )
        for row in rows
    ]


def evaluate_gate(
    db: Database,
    task_id: str,
    *,
    attempt_id: str | None,
) -> GateReport:
    """Evaluate whether ``task_id`` may transition ``VERIFYING -> DONE``.

    Pure inspection: it never mutates state, so it is safe to call from ``awayctl status``
    to preview why a task is stuck.

    A task with **zero required** requirements closes the gate rather than opening it.
    That is the single most important line in this function. The naive predicate "nothing
    required is unsatisfied, therefore proceed" is vacuously true for such a task, which
    would hand any planner that emitted all-optional verification an unlimited supply of
    free ``DONE``s -- precisely the failure this milestone exists to prevent. Task creation
    already refuses to admit such a task; this is the independent second check, because one
    layer is always one bug away from being bypassed.

    Attempt scoping is strict, including for ``manual`` requirements: an approval recorded
    against attempt #1 does not carry over to attempt #2. That is inconvenient by design.
    A retry exists precisely because the work changed, so a human's earlier sign-off no
    longer describes what is now on disk.
    """
    requirements = load_requirements(db, task_id)
    required = [r for r in requirements if r.required]
    optional = [r for r in requirements if not r.required]

    if attempt_id is None:
        # No live attempt means nothing produced evidence *for this run*, so there is
        # nothing to be satisfied by. Falling through would compare against rows whose
        # attempt_id is NULL and open the gate on evidence tied to no execution at all --
        # reachable through the documented rate-limit suspend path, which closes the
        # attempt while leaving the task in VERIFYING.
        return GateReport(
            task_id=task_id,
            attempt_id=None,
            satisfied=False,
            reason=GateReason.NO_ACTIVE_ATTEMPT,
            required_total=len(required),
            missing=tuple(sorted(r.id for r in required)),
            failed=(),
            stale=(),
            satisfied_ids=(),
            optional_failed=(),
        )

    missing: list[str] = []
    failed: list[str] = []
    stale: list[str] = []
    satisfied_ids: list[str] = []
    optional_failed: list[str] = []

    for requirement in optional:
        row = db.query_one(
            "SELECT result FROM evidence "
            " WHERE task_id = ? AND verification_id = ? AND requirement_spec_hash = ? "
            "   AND attempt_id IS ? ORDER BY id DESC LIMIT 1",
            (task_id, requirement.id, requirement.spec_hash, attempt_id),
        )
        if row is not None and EvidenceResult(str(row["result"])) is not EvidenceResult.PASS:
            optional_failed.append(requirement.id)

    for requirement in required:
        # Latest-wins within the attempt: a check re-run after a fix supersedes its own
        # earlier failure. Ordering by id is safe because the column is AUTOINCREMENT.
        # Filtering on type here as well as at record time is deliberate belt-and-braces:
        # a row written before this rule existed, or by some other path, still cannot
        # discharge a requirement it was never capable of proving.
        acceptable = sorted(e.value for e in COMPATIBLE_EVIDENCE_TYPES[requirement.type])
        placeholders = ",".join("?" * len(acceptable))
        row = db.query_one(
            "SELECT result FROM evidence "
            " WHERE task_id = ? "
            "   AND verification_id = ? "
            "   AND requirement_spec_hash = ? "
            "   AND attempt_id IS ? "
            f"   AND type IN ({placeholders}) "
            " ORDER BY id DESC LIMIT 1",
            (task_id, requirement.id, requirement.spec_hash, attempt_id, *acceptable),
        )

        if row is None:
            # Either way the gate blocks. The extra query only refines the diagnostic:
            # "a replan changed this check" and "nobody ever ran it" look identical in the
            # gate result but call for completely different operator responses.
            missing.append(requirement.id)
            superseded = db.query_one(
                "SELECT 1 FROM evidence  WHERE task_id = ? AND verification_id = ? LIMIT 1",
                (task_id, requirement.id),
            )
            if superseded is not None:
                stale.append(requirement.id)
            continue

        if EvidenceResult(str(row["result"])) is EvidenceResult.PASS:
            satisfied_ids.append(requirement.id)
        else:
            failed.append(requirement.id)

    if not required:
        reason = GateReason.NO_REQUIRED_REQUIREMENTS
        satisfied = False
    elif missing or failed:
        reason = GateReason.UNSATISFIED_REQUIRED
        satisfied = False
    else:
        reason = GateReason.SATISFIED
        satisfied = True

    return GateReport(
        task_id=task_id,
        attempt_id=attempt_id,
        satisfied=satisfied,
        reason=reason,
        required_total=len(required),
        missing=tuple(sorted(set(missing))),
        failed=tuple(sorted(set(failed))),
        stale=tuple(sorted(set(stale))),
        satisfied_ids=tuple(sorted(set(satisfied_ids))),
        optional_failed=tuple(sorted(set(optional_failed))),
    )
