"""Document validation: JSON Schema plus the invariants JSON Schema cannot express.

Two layers, deliberately separate:

* **Schema validation** checks the shape of a single document -- types, enums, required
  keys, the per-type conditional payloads on verification requirements.
* **Cross-object validation** checks facts that span documents or that compare two
  properties of one document: duplicate ids, dangling references, self-dependencies,
  cycles, ``updatedByPlanVersion >= createdByPlanVersion``, and the rule that a task must
  declare at least one *deterministic* required check.

The split matters because a schema that appears to guarantee something it cannot is worse
than one that stays quiet: a reader who trusts ``uniqueItems`` to enforce unique ids will
skip writing the check that actually enforces them. So the schemas document what they
cannot do, and this module does it.
"""

from __future__ import annotations

import functools
import json
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator

from claude_away.core.dag import TaskNode, validate_graph
from claude_away.core.models import TaskStatus, VerificationType
from claude_away.errors import (
    PlanVersionError,
    SchemaValidationError,
    ValidationError,
)

__all__ = [
    "DETERMINISTIC_VERIFICATION_TYPES",
    "config_schema",
    "task_proposal_schema",
    "task_schema",
    "validate_config_document",
    "validate_task_collection",
    "validate_task_document",
    "validate_task_proposal",
    "validate_verification_contract",
]

DETERMINISTIC_VERIFICATION_TYPES: frozenset[VerificationType] = frozenset(
    {
        VerificationType.COMMAND,
        VerificationType.ARTIFACT,
        VerificationType.GIT,
        VerificationType.MANUAL,
    }
)
"""Verification types that produce evidence not generated by a language model.

``review`` is excluded. STATE_MODEL is explicit that "tasks with deterministic acceptance
checks cannot replace those checks with an LLM opinion", so a required ``review`` may
supplement a deterministic check but can never be the only thing standing between a task
and ``DONE``.
"""


def _schema_dir() -> Path:
    """Locate the published JSON Schema files.

    Installed wheels carry them at ``claude_away/_schemas`` (see the ``force-include`` in
    pyproject.toml). Editable installs and source checkouts do not, so fall back to the
    repository's ``schemas/`` directory. Trying both keeps ``pip install -e .`` working
    without duplicating the files in the tree.
    """
    packaged = Path(__file__).resolve().parent.parent / "_schemas"
    if (packaged / "task.schema.json").is_file():
        return packaged

    for parent in Path(__file__).resolve().parents:
        candidate = parent / "schemas"
        if (candidate / "task.schema.json").is_file():
            return candidate

    raise FileNotFoundError(
        "could not locate Claude Away JSON schemas; expected either "
        "claude_away/_schemas/ (installed) or <repo>/schemas/ (source checkout)"
    )


@functools.cache
def _load(name: str) -> dict[str, Any]:
    with (_schema_dir() / name).open(encoding="utf-8") as handle:
        loaded: dict[str, Any] = json.load(handle)
    return loaded


def task_schema() -> dict[str, Any]:
    """The authoritative task record schema."""
    return _load("task.schema.json")


def config_schema() -> dict[str, Any]:
    return _load("config.schema.json")


def task_proposal_schema() -> dict[str, Any]:
    """The planner-submittable subset.

    Resolved as a standalone schema so that ``$ref`` targets inside ``$defs`` still work:
    the proposal definition is lifted to the root and the original ``$defs`` carried along.
    """
    root = task_schema()
    proposal = dict(root["$defs"]["taskProposal"])
    proposal["$defs"] = root["$defs"]
    proposal["$schema"] = root["$schema"]
    return proposal


def _validate_against(
    document: Mapping[str, Any], schema: Mapping[str, Any], *, label: str
) -> None:
    validator = Draft202012Validator(schema)
    errors = sorted(validator.iter_errors(document), key=lambda e: list(e.absolute_path))
    if not errors:
        return
    raise SchemaValidationError(
        f"{label} failed schema validation",
        errors=[
            {
                "path": "/".join(str(part) for part in error.absolute_path),
                "message": error.message,
                "validator": str(error.validator),
            }
            for error in errors
        ],
    )


def validate_task_document(document: Mapping[str, Any]) -> None:
    """Validate one authoritative task record, schema then cross-property invariants."""
    _validate_against(document, task_schema(), label="task")
    _validate_single_task_invariants(document)


def validate_task_proposal(document: Mapping[str, Any]) -> None:
    """Validate a planner-submitted proposal.

    The schema alone already refuses ``status``, timestamps and plan versions -- they are
    not declared properties and ``additionalProperties`` is false -- so a model cannot
    propose that its own work is finished.
    """
    _validate_against(document, task_proposal_schema(), label="task proposal")
    _validate_single_task_invariants(document)


def validate_verification_contract(
    verification: Sequence[Mapping[str, Any]], *, task_id: str = "<task>"
) -> None:
    """Enforce the rules a task's verification contract must satisfy at all times.

    Extracted so that *every* path which writes a contract runs it -- creation and replan
    alike. Checking only at creation left the replan path able to install a contract that
    creation itself would have refused.
    """
    required = [r for r in verification if bool(r.get("required"))]
    if not required:
        raise ValidationError(
            "task declares no required verification; DONE would be unreachable and, worse, "
            "a naive gate would treat it as trivially satisfied",
            task_id=task_id,
        )
    deterministic = [
        r
        for r in required
        if VerificationType(str(r.get("type"))) in DETERMINISTIC_VERIFICATION_TYPES
    ]
    if not deterministic:
        raise ValidationError(
            "every required verification is of type 'review'; an LLM opinion may "
            "supplement a deterministic check but may not be the only thing gating DONE",
            task_id=task_id,
        )


def _validate_single_task_invariants(document: Mapping[str, Any]) -> None:
    task_id = str(document.get("id", "<new>"))

    # -- verification requirement ids must be unique -----------------------------------
    verification: Sequence[Mapping[str, Any]] = document.get("verification", [])
    seen_verification: set[str] = set()
    duplicates: set[str] = set()
    for requirement in verification:
        identifier = str(requirement.get("id", ""))
        if identifier in seen_verification:
            duplicates.add(identifier)
        seen_verification.add(identifier)
    if duplicates:
        raise ValidationError(
            "duplicate verification requirement ids",
            task_id=task_id,
            duplicated=sorted(duplicates),
        )

    # -- acceptance criterion ids must be unique ---------------------------------------
    criteria: Sequence[Mapping[str, Any]] = document.get("acceptanceCriteria", [])
    seen_criteria: set[str] = set()
    duplicate_criteria: set[str] = set()
    for criterion in criteria:
        identifier = str(criterion.get("id", ""))
        if identifier in seen_criteria:
            duplicate_criteria.add(identifier)
        seen_criteria.add(identifier)
    if duplicate_criteria:
        raise ValidationError(
            "duplicate acceptance criterion ids",
            task_id=task_id,
            duplicated=sorted(duplicate_criteria),
        )

    # -- at least one required, deterministic check ------------------------------------
    validate_verification_contract(verification, task_id=task_id)

    # -- self dependency ---------------------------------------------------------------
    dependencies: Sequence[str] = document.get("dependencies", [])
    if task_id in dependencies:
        raise ValidationError("task depends on itself", task_id=task_id)

    # -- plan version monotonicity -----------------------------------------------------
    created_by = document.get("createdByPlanVersion")
    updated_by = document.get("updatedByPlanVersion")
    if created_by is not None and updated_by is not None and updated_by < created_by:
        raise PlanVersionError(
            "updatedByPlanVersion must be greater than or equal to createdByPlanVersion",
            task_id=task_id,
            created_by_plan_version=created_by,
            updated_by_plan_version=updated_by,
        )


def validate_task_collection(
    documents: Iterable[Mapping[str, Any]],
    *,
    known_project_ids: Iterable[str] | None = None,
    known_goal_ids: Iterable[str] | None = None,
) -> None:
    """Validate a whole set of tasks together.

    This is where the invariants that only exist *between* documents are enforced:
    duplicate task ids, dangling project/goal references, dangling dependencies and cycles.
    """
    tasks = list(documents)

    seen: set[str] = set()
    duplicated: set[str] = set()
    for document in tasks:
        validate_task_document(document)
        identifier = str(document["id"])
        if identifier in seen:
            duplicated.add(identifier)
        seen.add(identifier)
    if duplicated:
        raise ValidationError("duplicate task ids", duplicated=sorted(duplicated))

    if known_project_ids is not None:
        known_projects = set(known_project_ids)
        for document in tasks:
            if str(document["projectId"]) not in known_projects:
                raise ValidationError(
                    "task references an unknown project",
                    task_id=str(document["id"]),
                    project_id=str(document["projectId"]),
                )

    if known_goal_ids is not None:
        known_goals = set(known_goal_ids)
        for document in tasks:
            unknown = sorted(set(document["goalIds"]) - known_goals)
            if unknown:
                raise ValidationError(
                    "task references unknown goals",
                    task_id=str(document["id"]),
                    unknown_goal_ids=unknown,
                )

    # Dependency integrity and acyclicity, with the pre-deduplication lists passed through
    # so that a repeated dependency is reported as a duplicate rather than silently folded.
    nodes = {
        str(d["id"]): TaskNode(
            id=str(d["id"]),
            status=TaskStatus(str(d.get("status", TaskStatus.PENDING.value))),
            dependencies=tuple(d.get("dependencies", ())),
        )
        for d in tasks
    }
    raw = {str(d["id"]): list(d.get("dependencies", ())) for d in tasks}
    validate_graph(nodes, raw_dependencies=raw)


def validate_config_document(document: Mapping[str, Any]) -> None:
    """Validate a configuration document and its cross-object invariants."""
    _validate_against(document, config_schema(), label="config")

    projects = document.get("projects", [])
    project_ids = [str(p["id"]) for p in projects]
    _reject_duplicates(project_ids, "duplicate project ids", key="project_ids")

    goals = document.get("goals", [])
    goal_ids = [str(g["id"]) for g in goals]
    _reject_duplicates(goal_ids, "duplicate goal ids", key="goal_ids")

    execution = document.get("execution", {})
    lease_seconds = execution.get("leaseSeconds")
    heartbeat_seconds = execution.get("leaseHeartbeatSeconds")
    # A heartbeat interval that is not comfortably shorter than the lease guarantees
    # spurious expiries under any scheduling jitter at all.
    if (
        lease_seconds is not None
        and heartbeat_seconds is not None
        and heartbeat_seconds * 2 > lease_seconds
    ):
        raise ValidationError(
            "leaseHeartbeatSeconds must be at most half of leaseSeconds so that a "
            "single missed heartbeat cannot expire a healthy lease",
            lease_seconds=lease_seconds,
            lease_heartbeat_seconds=heartbeat_seconds,
        )


def _reject_duplicates(values: Sequence[str], message: str, *, key: str) -> None:
    seen: set[str] = set()
    duplicated: set[str] = set()
    for value in values:
        if value in seen:
            duplicated.add(value)
        seen.add(value)
    if duplicated:
        raise ValidationError(message, **{key: sorted(duplicated)})
